name: AKS and ACS login
description: Logs in to Azure subscription and Azure Container Registry
inputs:
    AZURE_CLIENT_ID_OIDC:
      description: 'Azure Client ID OIDC'
      required: true
    AZURE_TENANT_ID:
      description: 'Azure Tenant ID'
      required: true
    AZURE_SUBSCRIPTION_ID:
      description: 'Azure Subscription ID'
      required: true
    AZURE_CLIENT_ID:
      description: 'Azure Client ID'
      required: true
    AZURE_CLIENT_SECRET:
      description: 'Azure Client Secret'
      required: true
runs:
  using: composite
  steps:
  - name: Login to our Azure subscription.
    uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
    with:
      client-id: ${{ inputs.AZURE_CLIENT_ID_OIDC }}
      tenant-id: ${{ inputs.AZURE_TENANT_ID }}
      subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

  - name: Login to Azure Container Registry
    uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
    with:
      registry: adoptopenjdkacr.azurecr.io
      username: ${{ inputs.AZURE_CLIENT_ID }}
      password: ${{ inputs.AZURE_CLIENT_SECRET }}

  - name: Set the target Azure Kubernetes Service (AKS) cluster.
    uses: azure/aks-set-context@feeca6405be94202afcb1c395616ff29b1811b9f # v4.0.2
    with:
      resource-group: adopt-api
      cluster-name: aksff92
