name: Build Adoptium

on: [ push, pull_request ]

jobs:
  build:
    name: Build Adoptium
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
        distribution: 'adopt'

    - uses: actions/checkout@v2

    - name: Build app
      run: ./mvnw --batch-mode clean install jacoco:report jacoco:report-aggregate -P-adoptopenjdk,adoptium -Decosystem=adoptium

    - uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
