name: CI

on:
  pull_request:
    branches: [ main, production ]
  push:
    branches: [ main, production ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ecosystem: [adoptium, adoptopenjdk]

    steps:
    - name: Setup mvnw arguments
      run: |
        case ${{ matrix.ecosystem }} in
          adoptium) echo "ARGS=-Padoptium,-adoptopenjdk" >> $GITHUB_ENV ;;
          adoptopenjdk) echo "ARGS=-Padoptopenjdk,-adoptium" >> $GITHUB_ENV ;;
        esac

    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        persist-credentials: false

    - uses: actions/setup-java@5896cecc08fd8a1fbdfaf517e29b571164b031f7 # v4.2.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build app
      run: ./mvnw --batch-mode clean install ${{ env.ARGS }}
