name: Publish Assets

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # for Git to git push

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build app
        run: ./mvnw --batch-mode clean deploy

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Publish maven assets
        run: |
          ls
          rsync -r ./*/target/mvn-repo ./target/mvn-repo /tmp/
          git checkout --orphan maven || git checkout maven
          git reset .
          rm -r mvn-repo || true
          cp -r /tmp/mvn-repo ./
          ls
          git add mvn-repo
          git commit -a -m "add artifacts"
          git push origin maven
